# Generated by Django 3.2.9 on 2022-02-20 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qux_core', '0002_auto_20210713_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('filename', models.CharField(max_length=128)),
                ('filepath', models.CharField(max_length=256)),
                ('filehash', models.CharField(editable=False, max_length=16)),
                ('filedate', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Upload Log',
                'db_table': 'qux_log_upload',
            },
        ),
        migrations.CreateModel(
            name='QuxPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('app_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128, null=True)),
            ],
            options={
                'db_table': 'qux_permissions',
                'unique_together': {('app_name', 'name')},
            },
        ),
        migrations.CreateModel(
            name='QuxEntityPermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('app_name', models.CharField(max_length=128)),
                ('entity_name', models.CharField(max_length=128)),
                ('entity_id', models.IntegerField()),
                ('action', models.CharField(max_length=128)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_access_to', to=settings.AUTH_USER_MODEL)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qux_core.quxpermission')),
            ],
            options={
                'db_table': 'qux_entity_permission_log',
            },
        ),
        migrations.CreateModel(
            name='QuxEntityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('app_name', models.CharField(max_length=128)),
                ('entity_name', models.CharField(max_length=128)),
                ('entity_id', models.IntegerField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('authorized', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='can_access', to=settings.AUTH_USER_MODEL)),
                ('perm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qux_core.quxpermission')),
            ],
            options={
                'db_table': 'qux_entity_permission',
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('url', models.URLField(max_length=2048, verbose_name='URL')),
                ('original', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Original File Name')),
                ('filename', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Download File Name')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download Log',
                'db_table': 'qux_log_download',
            },
        ),
        migrations.CreateModel(
            name='CoreURLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('accesstoken', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('request', models.CharField(blank=True, max_length=255, null=True)),
                ('urlpath', models.CharField(max_length=500)),
                ('params', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('csrf', models.CharField(blank=True, max_length=255, null=True)),
                ('responsetype', models.CharField(blank=True, default='application/json', max_length=128, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authlog_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'URL Log',
                'verbose_name_plural': 'URL Log',
                'db_table': 'qux_log_url',
            },
        ),
        migrations.CreateModel(
            name='CoreCommLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('comm_type', models.CharField(choices=[('sms', 'sms'), ('email', 'email'), ('whatsapp', 'whatsapp')], default='email', max_length=16, verbose_name='Comm Type')),
                ('provider', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Service Provider')),
                ('sent_at', models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='Sent At')),
                ('sender', models.CharField(max_length=128)),
                ('to', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('cc', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('bcc', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('attrs', models.JSONField(blank=True, default=None, null=True, verbose_name='Attributes')),
                ('status', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication Log',
                'verbose_name_plural': 'Communication Log',
                'db_table': 'qux_log_comm',
            },
        ),
    ]
