# Generated by Django 3.2.15 on 2022-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QHookTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('owner', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=255)),
                ('target_url', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCESS', 'success'), ('FAIL', 'fail'), ('PENDING', 'pending')], default='PENDING', max_length=32)),
            ],
            options={
                'unique_together': {('identifier', 'target_url')},
            },
        ),
    ]
