# Generated by Django 5.2.4 on 2026-02-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qhook", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="qhooktarget",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="qhooktarget",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "success"),
                    ("FAIL", "fail"),
                    ("PENDING", "pending"),
                ],
                default="PENDING",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="qhooktarget",
            constraint=models.UniqueConstraint(
                fields=("identifier", "target_url"), name="unique_qhook_identifier_url"
            ),
        ),
        migrations.AlterModelTable(
            name="qhooktarget",
            table="qux_qhook_target",
        ),
    ]
