# Generated by Django 4.2.7 on 2024-02-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qux_token", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customtoken",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customtoken",
            name="is_deleted",
        ),
        migrations.AddField(
            model_name="customtoken",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
