# Generated by Django 5.2.4 on 2026-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qux_token", "0002_update_customtoken"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customtoken",
            table="qux_custom_token",
        ),
    ]
