# Generated by Django 6.0.5 on 2026-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QHookTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('owner', models.CharField(max_length=32)),
                ('event', models.CharField(max_length=255)),
                ('target_url', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=32)),
                ('attempts', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'success'), ('FAIL', 'fail'), ('PENDING', 'pending')], default='PENDING', max_length=32)),
            ],
            options={
                'db_table': 'qux_qhook_target',
                'constraints': [models.UniqueConstraint(fields=('identifier', 'target_url'), name='unique_qhook_identifier_url')],
            },
        ),
    ]
