# Generated by Django 4.0.7 on 2022-08-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True, default=None, max_length=11, null=True
                    ),
                ),
                (
                    "username_persistent",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("response_ms", models.PositiveIntegerField(default=0)),
                (
                    "path",
                    models.CharField(
                        db_index=True, help_text="url path", max_length=256
                    ),
                ),
                (
                    "view",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="method called by this endpoint",
                        max_length=256,
                        null=True,
                    ),
                ),
                (
                    "view_method",
                    models.CharField(
                        blank=True, db_index=True, max_length=256, null=True
                    ),
                ),
                ("remote_addr", models.GenericIPAddressField()),
                ("host", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("query_params", models.TextField(blank=True, null=True)),
                ("data", models.TextField(blank=True, null=True)),
                ("response", models.TextField(blank=True, null=True)),
                ("errors", models.TextField(blank=True, null=True)),
                (
                    "status_code",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "verbose_name": "API Request Log",
                "abstract": False,
            },
        ),
    ]
