# Generated by Django 6.0.5 on 2026-05-10 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "dtm_audited",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("total_urls", models.IntegerField(default=0)),
                ("total_errors", models.IntegerField(default=0)),
                ("total_warnings", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "SEO Audit",
                "verbose_name_plural": "SEO Audits",
                "db_table": "qux_seo_audit",
                "ordering": ["-dtm_created"],
            },
        ),
        migrations.CreateModel(
            name="SEOAuditURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("url", models.CharField(max_length=2048)),
                (
                    "status_code",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "canonical",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_url",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "og_image",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_site_name",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "twitter_image",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="qux_seo.seoaudit",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Audit URL",
                "verbose_name_plural": "SEO Audit URLs",
                "db_table": "qux_seo_audit_url",
            },
        ),
        migrations.CreateModel(
            name="SEOSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("name", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64)),
                ("domain", models.CharField(max_length=128)),
                (
                    "twitter",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Data",
                "verbose_name_plural": "Site Data",
                "db_table": "qux_seo_site",
            },
        ),
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("canonical", models.CharField(max_length=255)),
                (
                    "page_name",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sites.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Data",
                "verbose_name_plural": "Page Data",
                "db_table": "qux_seo_page",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("site", "canonical"), name="unique_site_canonical"
                    )
                ],
            },
        ),
    ]
