# Generated by Django 3.2.15 on 2022-10-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.CharField(max_length=17, unique=True)),
                ('order', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('description', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Task Status',
                'verbose_name_plural': 'Task Statuses',
                'db_table': 'task_status',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='QueuedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtm_created', models.DateTimeField(auto_now_add=True, verbose_name='DTM Created')),
                ('dtm_updated', models.DateTimeField(auto_now=True, verbose_name='DTM Updated')),
                ('slug', models.CharField(max_length=11, unique=True)),
                ('user', models.CharField(max_length=11)),
                ('task', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, default=None, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('content_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='qux_tasks.taskstatus')),
            ],
            options={
                'db_table': 'qux_task_queue',
            },
        ),
    ]
