# Generated by Django 4.1.5 on 2023-03-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qux_auth", "0002_preference_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyuser",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company",
            name="domain",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="slug",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.URLField(
                blank=True, default=None, max_length=1024, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="qux_auth.company",
            ),
        ),
        migrations.AlterField(
            model_name="companyuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
