# Generated by Django 4.1.7 on 2023-04-25 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("qux_auth", "0003_companyuser_is_admin_alter_company_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("slug", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=32, unique=True)),
                ("description", models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Service Mode",
                "verbose_name_plural": "Service Modes",
                "db_table": "qux_auth_service_mode",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="profiles",
                to="qux_auth.company",
            ),
        ),
    ]
