# Generated by Django 4.1.5 on 2023-06-14 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qux_auth", "0005_alter_profile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companyuser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="companyuser",
            name="user",
        ),
        migrations.DeleteModel(
            name="ServiceMode",
        ),
        migrations.DeleteModel(
            name="CompanyUser",
        ),
    ]
