# Generated by Django 5.2.9 on 2026-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qux_seo", "0002_auto_20210713_1524"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seopage",
            name="canonical",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="seopage",
            constraint=models.UniqueConstraint(
                fields=("site", "canonical"), name="unique_site_canonical"
            ),
        ),
    ]
