# Generated by Django 5.2.9 on 2026-02-09 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qux_seo", "0003_unique_site_canonical"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_urls", models.IntegerField(default=0)),
                ("total_errors", models.IntegerField(default=0)),
                ("total_warnings", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "SEO Audit",
                "verbose_name_plural": "SEO Audits",
                "db_table": "qux_seo_audit",
                "ordering": ["-dtm_created"],
            },
        ),
        migrations.CreateModel(
            name="SEOAuditURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dtm_created",
                    models.DateTimeField(auto_now_add=True, verbose_name="DTM Created"),
                ),
                (
                    "dtm_updated",
                    models.DateTimeField(auto_now=True, verbose_name="DTM Updated"),
                ),
                ("url", models.CharField(max_length=2048)),
                (
                    "status_code",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "canonical",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_url",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "og_image",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                (
                    "og_site_name",
                    models.CharField(
                        blank=True, default=None, max_length=256, null=True
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        blank=True, default=None, max_length=64, null=True
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True, default=None, max_length=512, null=True
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "twitter_image",
                    models.CharField(
                        blank=True, default=None, max_length=2048, null=True
                    ),
                ),
                ("errors", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="qux_seo.seoaudit",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Audit URL",
                "verbose_name_plural": "SEO Audit URLs",
                "db_table": "qux_seo_audit_url",
            },
        ),
    ]
